var colors = require("colors");

function Word() {
	this.word = '';
	this.placeholder = [];
	this.wordChoices = [
		{word: "tyrian", asked: false, category: "Person"}, 
		{word: "winterfell", asked: false, category: "Place"},
		{word: "joffrey", asked: false, category: "Person"},
		{word: "westeros", asked: false, category: "Place"},
		{word: "essos", asked: false, category: "Place"},
		{word: "braavos", asked: false, category: "Place"},
		{word: "targaryen", asked: false, category: "Name"},
		{word: "wildling", asked: false, category: "Group"},
		{word: "meereen", asked: false, category: "Place"},
		{word: "cersei", asked: false, category: "Person"},
		{word: "stark", asked: false, category: "Name"},
		{word: "daenarys", asked: false, category: "Person"},
		{word: "dragon", asked: false, category: "Animal"},
		{word: "snow", asked: false, category: "Name"},
		{word: "highgarden", asked: false, category: "Place"},
		{word: "baratheon", asked: false, category: "Name"},
		{word: "martell", asked: false, category: "Name"},
		{word: "greyjoy", asked: false, category: "Name"},
		{word: "khaleesi", asked: false, category: "Title"},
		{word: "drogo", asked: false, category: "Person"},
		{word: "unsullied", asked: false, category: "Group"},
		{word: "baelish", asked: false, category: "Name"},
		{word: "varys", asked: false, category: "Name"}
	];
	this.index;
	this.askCount = 0;
	this.indexSelect = function() {
		//chooses a number at random between 0 and the length of the wordChoices array
		this.index = Math.floor(Math.random() * this.wordChoices.length);
	}
	this.chooseWord = function() {
		this.indexSelect();
		//checks if the question at index has been asked yet. The asked property prevents the same question from being asked again before all other questions have been asked. 
		if(this.wordChoices[this.index].asked === false) {
			//sets the asked property to true
			this.wordChoices[this.index].asked = true;
			//sets the word property equal to wordChoices.word at the index generated by indexSelect();
			this.word = this.wordChoices[this.index].word;
			//increases askCount by one. askCount keeps track of how many unique questions were asked.
			this.askCount++
		}
		else {
			//if the question at index has been asked already...
			if(this.askCount <= 23) {
				//checks to see if there are any questions left hat have not been asked

				this.chooseWord();
			}
			else {
				//if there are no more unasked questions, it loops over the wordChoices array and resets all asked properties back to false and runs the function chooseWord function again. This prevents the game from stopping once all of the questions have been asked.
				for (var i = 0; i < this.wordChoices.length; i++) {
					this.wordChoices[i].asked = false;
					this.chooseWord();
				}
				this.askCount = 0;
			}
		}
	}
};

Word.prototype.display = function() {
	//loops over the word and pushes a dash into the placeholder array for each letter in the word. 
		for(var i = 0; i < this.word.length; i++) {
			this.placeholder.push(" _ ");
		}
		//adds style to the display word and converts from an array to a string
		console.log("\n" + colors.white.bold(this.placeholder.join("") + "\n"));
}

module.exports = Word;